name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install gcc
      run: sudo apt-get install gcc
    - name: make
      run: make makeexe
    - name: make run
      run: ./runtest
