name: Unit Testcases

on:
  workflow_run:
    workflows: 
     - Build Code
    types: 
      - completed
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install cunit
      run: apt-get update && apt-get install -y gcc libcunit1 libcunit1-dev
    - name: install gcc
      run: sudo apt-get install gcc
    - name: make test suite
      run: make makeunittestsuite
    - name: run testcase
      run: ./runtest
